rootPageId: 1
base: 'https://www.serendipitypic.com/'
baseVariants: {  }
languages:
  -
    title: Español
    enabled: true
    languageId: '0'
    base: /
    typo3Language: es
    locale: es_ES.UTF-8
    iso-639-1: es
    navigationTitle: Español
    hreflang: es-ES
    direction: ''
    flag: es
  -
    title: English
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en
    direction: ''
    fallbackType: strict
    fallbacks: '0'
    flag: us
errorHandling: {  }
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent:*\r\nDisallow:/contacto/gracias-por-tu-mensaje\r\nDisallow:/typo3/"
  -
    route: sitemap.xml
    type: uri
    source: 'https://www.serendipitypic.com/?type=1533906435'
  -
    route: en/sitemap.xml
    type: uri
    source: 'https://www.serendipitypic.com/en/?type=1533906435'
  -
    route: /en/robots.txt
    type: staticText
    content: "User-agent:*\r\nDisallow:/en/contact/thanks-for-your-message\r\nDisallow:/typo3/"
